// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeRepository.API.Data;

#nullable disable

namespace RecipeRepository.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240317142028_Add Relationships")]
    partial class AddRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergenCategoryRecipeDetails", b =>
                {
                    b.Property<Guid>("AllergenCategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AllergenCategoriesId", "RecipeDetailsId");

                    b.HasIndex("RecipeDetailsId");

                    b.ToTable("AllergenCategoryRecipeDetails");
                });

            modelBuilder.Entity("MealCategoryRecipeDetails", b =>
                {
                    b.Property<Guid>("MealCategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MealCategoriesId", "RecipeDetailsId");

                    b.HasIndex("RecipeDetailsId");

                    b.ToTable("MealCategoryRecipeDetails");
                });

            modelBuilder.Entity("RecipeRepository.API.Models.Domain.AllergenCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllergenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllergenUrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AllergenCategories");
                });

            modelBuilder.Entity("RecipeRepository.API.Models.Domain.MealCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealUrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealCategories");
                });

            modelBuilder.Entity("RecipeRepository.API.Models.Domain.RecipeDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipeContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeUrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isVisible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RecipeDetails");
                });

            modelBuilder.Entity("AllergenCategoryRecipeDetails", b =>
                {
                    b.HasOne("RecipeRepository.API.Models.Domain.AllergenCategory", null)
                        .WithMany()
                        .HasForeignKey("AllergenCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeRepository.API.Models.Domain.RecipeDetails", null)
                        .WithMany()
                        .HasForeignKey("RecipeDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealCategoryRecipeDetails", b =>
                {
                    b.HasOne("RecipeRepository.API.Models.Domain.MealCategory", null)
                        .WithMany()
                        .HasForeignKey("MealCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeRepository.API.Models.Domain.RecipeDetails", null)
                        .WithMany()
                        .HasForeignKey("RecipeDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
